---
sudo: requred

language: python
python: "2.7"

env:
- distribution: centos
  version: 7
  init: /lib/systemd/systemd

services:
- docker

before_install:
- 'sudo docker pull ${distribution}:${version}'

install:
- pip install ansible
- pip install ansible-lint

script:
- container_id=$(mktemp)
- 'sudo docker run --detach --volume="${PWD}":/etc/ansible/roles/microsoft_packages:ro ${distribution}:${version} "init" > "${container_id}"'
- 'sudo docker exec "$(cat ${container_id})" env ANSIBLE_FORCE_COLOR=1 ansible-playbook -v tests/test.yml --syntax-check'
- 'sudo docker exec "$(cat ${container_id})" env ANSIBLE_FORCE_COLOR=1 ansible-playbook -v tests/test.yml'
