---
sudo: requred

language: python
python: "2.7"

env:
- distribution: centos
  version: 7
  init: /lib/systemd/systemd

services:
- docker

before_install:
- 'sudo docker pull ${distribution}:${version}'
- 'sudo docker build --no-cache --rm --file=travis/Dockerfile.${distribution}-${version} --tag=${distribution}-${version}:ansible travis'

install:
- pip install ansible
- pip install ansible-lint

script:
- container_id=$(mktemp)
- 'sudo docker run --detach --privileged -v /sys/fs/cgroup:/sys/fs/cgroup:ro --volume="${PWD}":/etc/ansible/roles/microsoft_packages:ro ${distribution}-${version}:ansible > "${container_id}"'
- ls -l /etc/ansible/roles
- 'sudo docker exec "$(cat ${container_id})" env ANSIBLE_FORCE_COLOR=1 ansible-playbook -v /etc/ansible/roles/microsoft_packages/tests/test.yml --syntax-check'
