---
sudo: requred

language: python
python: "2.7"

env:
- ANSIBLE_VERSION=latest

before_install:

install:
- pip install ansible
- pip install ansible-lint

script:
- ansible-playbook -i tests/inventory tests/test.yml --syntax-check
- ansible-playbook -i tests/inventory tests/test.yml -vvvv
